version: '3'
services:
  db :
    image: postgres:16.0
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=voosh-backend-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=s3cret123

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
